;;; eaf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eaf.el

(autoload 'eaf-open-bookmark "eaf" "\
Command to open or create EAF bookmarks with completion." t)
(autoload 'eaf-get-file-name-extension "eaf" "\
A wrapper around `file-name-extension' that downcases the extension of the FILE.

(fn FILE)")
(autoload 'eaf-open "eaf" "\
Open an EAF application with URL, optional APP-NAME and ARGS.

Interactively, a prefix arg replaces ALWAYS-NEW, which means to open a new
 buffer regardless of whether a buffer with existing URL and APP-NAME exists.

By default, `eaf-open' will switch to buffer if corresponding url exists.
`eaf-open' always open new buffer if option OPEN-ALWAYS is non-nil.

When called interactively, URL accepts a file that can be opened by EAF.

(fn URL &optional APP-NAME ARGS ALWAYS-NEW)" t)
(autoload 'eaf-install-and-update "eaf" "\
Interactively run `install-eaf.py' to install/update EAF apps.

For a full `install-eaf.py' experience, refer to `--help' and run in a terminal.

(fn &rest APPS)" t)
(register-definition-prefixes "eaf" '("eaf-" "get-emacs-face-foregrounds"))

;;; End of scraped data

(provide 'eaf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eaf-autoloads.el ends here
