;;; exwm-firefox-core-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from exwm-firefox-core.el

(autoload 'exwm-firefox-core-up "exwm-firefox-core" "\
Move up." t)
(autoload 'exwm-firefox-core-down "exwm-firefox-core" "\
Move down." t)
(autoload 'exwm-firefox-core-left "exwm-firefox-core" "\
Move left." t)
(autoload 'exwm-firefox-core-right "exwm-firefox-core" "\
Move right." t)
(autoload 'exwm-firefox-core-up-select "exwm-firefox-core" "\
Move up and select." t)
(autoload 'exwm-firefox-core-down-select "exwm-firefox-core" "\
Move down and select." t)
(autoload 'exwm-firefox-core-left-select "exwm-firefox-core" "\
Move left and select." t)
(autoload 'exwm-firefox-core-right-select "exwm-firefox-core" "\
Move right and select." t)
(autoload 'exwm-firefox-core-top "exwm-firefox-core" "\
Move to top of page." t)
(autoload 'exwm-firefox-core-bottom "exwm-firefox-core" "\
Move to bottom of page." t)
(autoload 'exwm-firefox-core-bottom-select "exwm-firefox-core" "\
Move to bottom of page and select." t)
(autoload 'exwm-firefox-core-page-up "exwm-firefox-core" "\
Move one page up." t)
(autoload 'exwm-firefox-core-page-down "exwm-firefox-core" "\
Move one page down." t)
(autoload 'exwm-firefox-core-page-down-select "exwm-firefox-core" "\
Move one page down and select." t)
(autoload 'exwm-firefox-core-half-page-down "exwm-firefox-core" "\
Move down half a page." t)
(autoload 'exwm-firefox-core-half-page-up "exwm-firefox-core" "\
Move up half a page." t)
(autoload 'exwm-firefox-core-half-page-down-select "exwm-firefox-core" "\
Move down half a page and select." t)
(autoload 'exwm-firefox-core-half-page-up-select "exwm-firefox-core" "\
Move up half a page and select." t)
(autoload 'exwm-firefox-core-history-forward "exwm-firefox-core" "\
Forward in history.

(fn &optional ARG)" t)
(autoload 'exwm-firefox-core-history-back "exwm-firefox-core" "\
Back in history.

(fn &optional ARG)" t)
(autoload 'exwm-firefox-core-history-sidebar "exwm-firefox-core" "\
Forward in history." t)
(autoload 'exwm-firefox-core-history-menu "exwm-firefox-core" "\
Forward in history." t)
(autoload 'exwm-firefox-core-home-page "exwm-firefox-core" "\
Goto home page." t)
(autoload 'exwm-firefox-core-reload "exwm-firefox-core" "\
Reload page." t)
(autoload 'exwm-firefox-core-reload-override-cache "exwm-firefox-core" "\
Reload page, override cache." t)
(autoload 'exwm-firefox-core-tab-close "exwm-firefox-core" "\
Close tab." t)
(autoload 'exwm-firefox-core-tab-close-undo "exwm-firefox-core" "\
Undo close tab." t)
(autoload 'exwm-firefox-core-tab-new "exwm-firefox-core" "\
New tab." t)
(autoload 'exwm-firefox-core-tab-next "exwm-firefox-core" "\
Next tab." t)
(autoload 'exwm-firefox-core-tab-previous "exwm-firefox-core" "\
Previous tab." t)
(autoload 'exwm-firefox-core-tab-first "exwm-firefox-core" "\
First tab." t)
(autoload 'exwm-firefox-core-tab-last "exwm-firefox-core" "\
Last tab." t)
(autoload 'exwm-firefox-core-tab-move-right "exwm-firefox-core" "\
Move tab right." t)
(autoload 'exwm-firefox-core-tab-move-left "exwm-firefox-core" "\
Move tab left." t)
(autoload 'exwm-firefox-core-tab-mute "exwm-firefox-core" "\
Mute tab." t)
(autoload 'exwm-firefox-core-window-new "exwm-firefox-core" "\
New window." t)
(autoload 'exwm-firefox-core-window-new-private "exwm-firefox-core" "\
New private window." t)
(autoload 'exwm-firefox-core-window-close "exwm-firefox-core" "\
Close window." t)
(autoload 'exwm-firefox-core-window-close-undo "exwm-firefox-core" "\
Undo close window." t)
(autoload 'exwm-firefox-core-find "exwm-firefox-core" "\
Find." t)
(autoload 'exwm-firefox-core-quick-find "exwm-firefox-core" "\
Quick find." t)
(autoload 'exwm-firefox-core-find-next "exwm-firefox-core" "\
Find next." t)
(autoload 'exwm-firefox-core-find-previous "exwm-firefox-core" "\
Find previous." t)
(autoload 'exwm-firefox-core-copy "exwm-firefox-core" "\
Copy text." t)
(autoload 'exwm-firefox-core-cut "exwm-firefox-core" "\
Cut text." t)
(autoload 'exwm-firefox-core-paste "exwm-firefox-core" "\
Paste text." t)
(autoload 'exwm-firefox-core-delete "exwm-firefox-core" "\
Delete text." t)
(autoload 'exwm-firefox-core-undo "exwm-firefox-core" "\
Undo." t)
(autoload 'exwm-firefox-core-redo "exwm-firefox-core" "\
Redo." t)
(autoload 'exwm-firefox-core-forward-word "exwm-firefox-core" "\
Move word forward." t)
(autoload 'exwm-firefox-core-back-word "exwm-firefox-core" "\
Move word backward." t)
(autoload 'exwm-firefox-core-forward-word-select "exwm-firefox-core" "\
Move word forward and select." t)
(autoload 'exwm-firefox-core-back-word-select "exwm-firefox-core" "\
Move word backward and select." t)
(autoload 'exwm-firefox-core-select-all "exwm-firefox-core" "\
Select whole page." t)
(autoload 'exwm-firefox-core-bookmark-new "exwm-firefox-core" "\
Create new bookmark." t)
(autoload 'exwm-firefox-core-bookmark-sidebar "exwm-firefox-core" "\
Open bookmark sidebar." t)
(autoload 'exwm-firefox-core-bookmark-menu "exwm-firefox-core" "\
Open bookmark menu." t)
(autoload 'exwm-firefox-core-focus-search-bar "exwm-firefox-core" "\
Toggle focus between the search bar and the page." t)
(autoload 'exwm-firefox-core-toggle-focus-search-bar "exwm-firefox-core" "\
Toggle focus between the search bar and the page." t)
(autoload 'exwm-firefox-core-cancel "exwm-firefox-core" "\
General cancel action." t)
(autoload 'exwm-firefox-core-open-file "exwm-firefox-core" "\
Open file." t)
(autoload 'exwm-firefox-core-save-page "exwm-firefox-core" "\
Save page to file." t)
(autoload 'exwm-firefox-core-quit "exwm-firefox-core" "\
Quit firefox." t)
(autoload 'exwm-firefox-core-downloads-menu "exwm-firefox-core" "\
Open downloads menu." t)
(autoload 'exwm-firefox-core-reader-mode "exwm-firefox-core" "\
Open current page in firefox reader-mode." t)
(register-definition-prefixes "exwm-firefox-core" '("exwm-firefox-core-"))

;;; End of scraped data

(provide 'exwm-firefox-core-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; exwm-firefox-core-autoloads.el ends here
